export const MAX_CONTEXT_MESSAGES = 20;

export const MAX_CONVERSATION_MESSAGES = 40;

export const CONVERSATION_INACTIVITY_HOURS = 4;

export const CONVERSATION_INACTIVITY_MS = CONVERSATION_INACTIVITY_HOURS * 60 * 60 * 1000;